export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-zinc-950 text-zinc-100">{children}</body>
    </html>
  );
}
