export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export const dynamic = "force-dynamic";

import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-zinc-950 text-zinc-100 transition-colors duration-500">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
